// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVSYqwd0voqvWTE2Xf78jLGWBJS0yM0ew',
    appId: '1:1036537089082:web:01a4bbc9c6b192ec2eb903',
    messagingSenderId: '1036537089082',
    projectId: 'finsight-e0fe3',
    authDomain: 'finsight-e0fe3.firebaseapp.com',
    storageBucket: 'finsight-e0fe3.firebasestorage.app',
    measurementId: 'G-FT61PC2F78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2y9KwuEF1tTxVhoaMon1yV_2EpZcTuRQ',
    appId: '1:1036537089082:android:14db2f90f85ef9b42eb903',
    messagingSenderId: '1036537089082',
    projectId: 'finsight-e0fe3',
    storageBucket: 'finsight-e0fe3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVSYqwd0voqvWTE2Xf78jLGWBJS0yM0ew',
    appId: '1:1036537089082:web:dbe779053760778e2eb903',
    messagingSenderId: '1036537089082',
    projectId: 'finsight-e0fe3',
    authDomain: 'finsight-e0fe3.firebaseapp.com',
    storageBucket: 'finsight-e0fe3.firebasestorage.app',
    measurementId: 'G-7LXBN8Q4EZ',
  );
}
